<!DOCTYPE html><html lang="en-US" prefix="og: https://ogp.me/ns#"><!-- Mirrored from developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 08 Jan 2025 13:10:15 GMT --><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="https://developer.mozilla.org/favicon-48x48.bc390275e955dacb2e65.png"><link rel="apple-touch-icon" href="https://developer.mozilla.org/apple-touch-icon.528534bba673c38049c2.png"><meta name="theme-color" content="#ffffff"><link rel="manifest" href="https://developer.mozilla.org/manifest.f42880861b394dd4dc9b.json"><link rel="search" type="application/opensearchdescription+xml" href="https://developer.mozilla.org/opensearch.xml" title="MDN Web Docs"><title>Promise.prototype.catch()</title><link rel="alternate" title="Promise.prototype.catch()" href="https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" hreflang="de"><link rel="alternate" title="Promise.prototype.catch()" href="https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" hreflang="es"><link rel="alternate" title="Promise.prototype.catch()" href="https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" hreflang="fr"><link rel="alternate" title="Promise.prototype.catch()" href="https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" hreflang="ja"><link rel="alternate" title="Promise.prototype.catch()" href="https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" hreflang="ko"><link rel="alternate" title="Promise.prototype.catch()" href="https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" hreflang="pt"><link rel="alternate" title="Promise.prototype.catch()" href="https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" hreflang="ru"><link rel="alternate" title="Promise.prototype.catch()" href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" hreflang="zh"><link rel="alternate" title="Promise.prototype.catch()" href="https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch" hreflang="zh-Hant"><link rel="alternate" title="Promise.prototype.catch()" href="catch.html" hreflang="en"><link rel="preload" as="font" type="font/woff2" href="https://developer.mozilla.org/static/media/Inter.var.c2fe3cb2b7c746f7966a.woff2" crossorigin=""><link rel="alternate" type="application/rss+xml" title="MDN Blog RSS Feed" href="https://developer.mozilla.org/en-US/blog/rss.xml" hreflang="en"><meta name="description" content="The catch() method of Promise instances schedules a function to be called when the promise is rejected. It immediately returns another Promise object, allowing you to chain calls to other promise methods. It is a shortcut for then(undefined, onRejected)."><meta property="og:url" content="catch.html"><meta property="og:title" content="Promise.prototype.catch() - JavaScript | MDN"><meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:description" content="The catch() method of Promise instances schedules a function to be called when the promise is rejected. It immediately returns another Promise object, allowing you to chain calls to other promise methods. It is a shortcut for then(undefined, onRejected)."><meta property="og:image" content="https://developer.mozilla.org/mdn-social-share.d893525a4fb5fb1f67a2.png"><meta property="og:image:type" content="image/png"><meta property="og:image:height" content="1080"><meta property="og:image:width" content="1920"><meta property="og:image:alt" content="The MDN Web Docs logo, featuring a blue accent color, displayed on a solid black background."><meta property="og:site_name" content="MDN Web Docs"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:creator" content="MozDevNet"><link rel="canonical" href="catch.html"><style media="print">.article-actions-container,.document-toc-container,.language-menu,.main-menu-toggle,.on-github,.page-footer,.place,.sidebar,.top-banner,.top-navigation-main,ul.prev-next{display:none!important}.main-page-content,.main-page-content pre{padding:2px}.main-page-content pre{border-left-width:2px}</style><link href="https://developer.mozilla.org/static/css/main.65aa8eed.css" rel="stylesheet"></head><body><script>if(document.body.addEventListener("load",(t=>{t.target.classList.contains("interactive")&&t.target.setAttribute("data-readystate","complete")}),{capture:!0}),window&&document.documentElement){const t={light:"#ffffff",dark:"#1b1b1b"};try{const e=window.localStorage.getItem("theme");e&&(document.documentElement.className=e,document.documentElement.style.backgroundColor=t[e]);const o=window.localStorage.getItem("nop");o&&(document.documentElement.dataset.nop=o)}catch(t){console.warn("Unable to read theme from localStorage",t)}}</script><div id="root"><div class="page-wrapper  category-javascript document-page"><div class="main-wrapper"><main id="content" class="main-content  "><article class="main-page-content" lang="en-US"><header><h1>Promise.prototype.catch()</h1><details class="baseline-indicator high"><summary><span class="indicator" role="img" aria-label="Baseline Check"></span><h2>Baseline<!-- --> <span class="not-bold">Widely available</span></h2><div class="browsers"><span class="engine" title="Supported in Chrome and Edge"><span class="browser chrome supported" role="img" aria-label="Chrome check"></span><span class="browser edge supported" role="img" aria-label="Edge check"></span></span><span class="engine" title="Supported in Firefox"><span class="browser firefox supported" role="img" aria-label="Firefox check"></span></span><span class="engine" title="Supported in Safari"><span class="browser safari supported" role="img" aria-label="Safari check"></span></span></div><span class="icon icon-chevron "></span></summary><div class="extra"><p>This feature is well established and works across many devices and browser versions. It’s been available across browsers since<!-- --> <!-- -->July 2015<!-- -->.</p><ul><li><a href="https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility" data-glean="baseline_link_learn_more" target="_blank" class="learn-more">Learn more</a></li><li><a href="#browser_compatibility" data-glean="baseline_link_bcd_table">See full compatibility</a></li><li><a href="https://survey.alchemer.com/s3/7634825/MDN-baseline-feedback?page=%2Fen-US%2Fdocs%2FWeb%2FJavaScript%2FReference%2FGlobal_Objects%2FPromise%2Fcatch&amp;level=high" data-glean="baseline_link_feedback" class="feedback-link" target="_blank" rel="noreferrer">Report feedback</a></li></ul></div></details></header><div class="section-content"><p>The <strong><code>catch()</code></strong> method of <a href="../Promise.html"><code>Promise</code></a> instances schedules a function to be called when the promise is rejected. It immediately returns another <a href="../Promise.html"><code>Promise</code></a> object, allowing you to <a href="../../../Guide/Using_promises.html#chaining">chain</a> calls to other promise methods. It is a shortcut for <a href="then.html"><code>then(undefined, onRejected)</code></a>.</p></div><section aria-labelledby="try_it"><h2 id="try_it"><a href="#try_it">Try it</a></h2><div class="section-content"><iframe class="interactive is-js-height" height="200" src="https://interactive-examples.mdn.mozilla.net/pages/js/promise-catch.html" title="MDN Web Docs Interactive Example" allow="clipboard-write" loading="lazy"></iframe></div></section><section aria-labelledby="syntax"><h2 id="syntax"><a href="#syntax">Syntax</a></h2><div class="section-content"><div class="code-example"><div class="example-header"><span class="language-name">js</span></div><pre class="brush: js notranslate"><code>promiseInstance.catch(onRejected)
</code></pre></div></div></section><section aria-labelledby="parameters"><h3 id="parameters"><a href="#parameters">Parameters</a></h3><div class="section-content"><dl>
<dt id="onrejected"><a href="#onrejected"><code>onRejected</code></a></dt>
<dd>
<p>A function to asynchronously execute when this promise becomes rejected. Its return value becomes the fulfillment value of the promise returned by <code>catch()</code>. The function is called with the following arguments:</p>
<dl>
<dt id="reason"><a href="#reason"><code>reason</code></a></dt>
<dd>
<p>The value that the promise was rejected with.</p>
</dd>
</dl>
</dd>
</dl></div></section><section aria-labelledby="return_value"><h3 id="return_value"><a href="#return_value">Return value</a></h3><div class="section-content"><p>Returns a new <a href="../Promise.html"><code>Promise</code></a>. This new promise is always pending when returned, regardless of the current promise's status. If <code>onRejected</code> is called, the returned promise will resolve based on the return value of this call, or reject with the thrown error from this call. If the current promise fulfills, <code>onRejected</code> is not called and the returned promise fulfills to the same value.</p></div></section><section aria-labelledby="description"><h2 id="description"><a href="#description">Description</a></h2><div class="section-content"><p>The <code>catch</code> method is used for error handling in promise composition. Since it returns a <a href="../Promise.html"><code>Promise</code></a>, it <a href="../../../Guide/Using_promises.html#chaining_after_a_catch">can be chained</a> in the same way as its sister method, <a href="then.html"><code>then()</code></a>.</p>
<p>If a promise becomes rejected, and there are no rejection handlers to call (a handler can be attached through any of <a href="then.html"><code>then()</code></a>, <code>catch()</code>, or <a href="finally.html"><code>finally()</code></a>), then the rejection event is surfaced by the host. In the browser, this results in an <a href="https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event"><code>unhandledrejection</code></a> event. If a handler is attached to a rejected promise whose rejection has already caused an unhandled rejection event, then another <a href="https://developer.mozilla.org/en-US/docs/Web/API/Window/rejectionhandled_event"><code>rejectionhandled</code></a> event is fired.</p>
<p><code>catch()</code> internally calls <code>then()</code> on the object upon which it was called, passing <code>undefined</code> and <code>onRejected</code> as arguments. The value of that call is directly returned. This is observable if you wrap the methods.</p>
<div class="code-example"><div class="example-header"><span class="language-name">js</span></div><pre class="brush: js notranslate"><code>// overriding original Promise.prototype.then/catch just to add some logs
((Promise) =&gt; {
  const originalThen = Promise.prototype.then;
  const originalCatch = Promise.prototype.catch;

  Promise.prototype.then = function (...args) {
    console.log("Called .then on %o with arguments: %o", this, args);
    return originalThen.apply(this, args);
  };
  Promise.prototype.catch = function (...args) {
    console.error("Called .catch on %o with arguments: %o", this, args);
    return originalCatch.apply(this, args);
  };
})(Promise);

// calling catch on an already resolved promise
Promise.resolve().catch(function XXX() {});

// Logs:
// Called .catch on Promise{} with arguments: Arguments{1} [0: function XXX()]
// Called .then on Promise{} with arguments: Arguments{2} [0: undefined, 1: function XXX()]
</code></pre></div>
<p>This means that passing <code>undefined</code> still causes the returned promise to be rejected, and you have to pass a function to prevent the final promise from being rejected.</p>
<p>Because <code>catch()</code> just calls <code>then()</code>, it supports subclassing.</p>
<div class="notecard note">
<p><strong>Note:</strong>
The examples below are throwing instances of <a href="../Error.html"><code>Error</code></a>. As with synchronous <a href="../../Statements/throw.html"><code>throw</code></a> statements, this is considered a good practice; otherwise, the part doing the catching would have to perform checks to see if the argument was a string or an error, and you might lose valuable information such as stack traces.</p>
</div></div></section><section aria-labelledby="examples"><h2 id="examples"><a href="#examples">Examples</a></h2><div class="section-content"></div></section><section aria-labelledby="using_and_chaining_the_catch_method"><h3 id="using_and_chaining_the_catch_method"><a href="#using_and_chaining_the_catch_method">Using and chaining the catch() method</a></h3><div class="section-content"><div class="code-example"><div class="example-header"><span class="language-name">js</span></div><pre class="brush: js notranslate"><code>const p1 = new Promise((resolve, reject) =&gt; {
  resolve("Success");
});

p1.then((value) =&gt; {
  console.log(value); // "Success!"
  throw new Error("oh, no!");
})
  .catch((e) =&gt; {
    console.error(e.message); // "oh, no!"
  })
  .then(
    () =&gt; console.log("after a catch the chain is restored"), // "after a catch the chain is restored"
    () =&gt; console.log("Not fired due to the catch"),
  );

// The following behaves the same as above
p1.then((value) =&gt; {
  console.log(value); // "Success!"
  return Promise.reject("oh, no!");
})
  .catch((e) =&gt; {
    console.error(e); // "oh, no!"
  })
  .then(
    () =&gt; console.log("after a catch the chain is restored"), // "after a catch the chain is restored"
    () =&gt; console.log("Not fired due to the catch"),
  );
</code></pre></div></div></section><section aria-labelledby="gotchas_when_throwing_errors"><h3 id="gotchas_when_throwing_errors"><a href="#gotchas_when_throwing_errors">Gotchas when throwing errors</a></h3><div class="section-content"><p>Throwing an error will call the <code>catch()</code> method most of the time:</p>
<div class="code-example"><div class="example-header"><span class="language-name">js</span></div><pre class="brush: js notranslate"><code>const p1 = new Promise((resolve, reject) =&gt; {
  throw new Error("Uh-oh!");
});

p1.catch((e) =&gt; {
  console.error(e); // "Uh-oh!"
});
</code></pre></div>
<p>Errors thrown inside asynchronous functions will act like uncaught errors:</p>
<div class="code-example"><div class="example-header"><span class="language-name">js</span></div><pre class="brush: js notranslate"><code>const p2 = new Promise((resolve, reject) =&gt; {
  setTimeout(() =&gt; {
    throw new Error("Uncaught Exception!");
  }, 1000);
});

p2.catch((e) =&gt; {
  console.error(e); // This is never called
});
</code></pre></div>
<p>Errors thrown after <code>resolve</code> is called will be silenced:</p>
<div class="code-example"><div class="example-header"><span class="language-name">js</span></div><pre class="brush: js notranslate"><code>const p3 = new Promise((resolve, reject) =&gt; {
  resolve();
  throw new Error("Silenced Exception!");
});

p3.catch((e) =&gt; {
  console.error(e); // This is never called
});
</code></pre></div></div></section><section aria-labelledby="catch_is_not_called_if_the_promise_is_fulfilled"><h3 id="catch_is_not_called_if_the_promise_is_fulfilled"><a href="#catch_is_not_called_if_the_promise_is_fulfilled">catch() is not called if the promise is fulfilled</a></h3><div class="section-content"><div class="code-example"><div class="example-header"><span class="language-name">js</span></div><pre class="brush: js notranslate"><code>// Create a promise which would not call onReject
const p1 = Promise.resolve("calling next");

const p2 = p1.catch((reason) =&gt; {
  // This is never called
  console.error("catch p1!");
  console.error(reason);
});

p2.then(
  (value) =&gt; {
    console.log("next promise's onFulfilled");
    console.log(value); // calling next
  },
  (reason) =&gt; {
    console.log("next promise's onRejected");
    console.log(reason);
  },
);
</code></pre></div></div></section><h2 id="specifications"><a href="#specifications">Specifications</a></h2><table class="standard-table"><thead><tr><th scope="col">Specification</th></tr></thead><tbody><tr><td><a href="https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise.prototype.catch">ECMAScript Language Specification<!-- --> <br><small># <!-- -->sec-promise.prototype.catch</small></a></td></tr></tbody></table><h2 id="browser_compatibility"><a href="#browser_compatibility">Browser compatibility</a></h2><p>BCD tables only load in the browser<noscript> <!-- -->with JavaScript enabled. Enable JavaScript to view data.</noscript></p><section aria-labelledby="see_also"><h2 id="see_also"><a href="#see_also">See also</a></h2><div class="section-content"><ul>
<li><a href="../Promise.html"><code>Promise</code></a></li>
<li><a href="then.html"><code>Promise.prototype.then()</code></a></li>
<li><a href="finally.html"><code>Promise.prototype.finally()</code></a></li>
</ul></div></section></article></main></div></div></div><script type="application/json" id="hydration">{"url":"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch","doc":{"body":[{"type":"prose","value":{"id":null,"title":null,"isH3":false,"content":"<p>The <strong><code>catch()</code></strong> method of <a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise\"><code>Promise</code></a> instances schedules a function to be called when the promise is rejected. It immediately returns another <a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise\"><code>Promise</code></a> object, allowing you to <a href=\"/en-US/docs/Web/JavaScript/Guide/Using_promises#chaining\">chain</a> calls to other promise methods. It is a shortcut for <a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then\"><code>then(undefined, onRejected)</code></a>.</p>"}},{"type":"prose","value":{"id":"try_it","title":"Try it","isH3":false,"content":"<iframe class=\"interactive is-js-height\" height=\"200\" src=\"https://interactive-examples.mdn.mozilla.net/pages/js/promise-catch.html\" title=\"MDN Web Docs Interactive Example\" allow=\"clipboard-write\" loading=\"lazy\"></iframe>"}},{"type":"prose","value":{"id":"syntax","title":"Syntax","isH3":false,"content":"<div class=\"code-example\"><div class=\"example-header\"><span class=\"language-name\">js</span></div><pre class=\"brush: js notranslate\"><code>promiseInstance.catch(onRejected)\n</code></pre></div>"}},{"type":"prose","value":{"id":"parameters","title":"Parameters","isH3":true,"content":"<dl>\n<dt id=\"onrejected\"><a href=\"#onrejected\"><code>onRejected</code></a></dt>\n<dd>\n<p>A function to asynchronously execute when this promise becomes rejected. Its return value becomes the fulfillment value of the promise returned by <code>catch()</code>. The function is called with the following arguments:</p>\n<dl>\n<dt id=\"reason\"><a href=\"#reason\"><code>reason</code></a></dt>\n<dd>\n<p>The value that the promise was rejected with.</p>\n</dd>\n</dl>\n</dd>\n</dl>"}},{"type":"prose","value":{"id":"return_value","title":"Return value","isH3":true,"content":"<p>Returns a new <a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise\"><code>Promise</code></a>. This new promise is always pending when returned, regardless of the current promise's status. If <code>onRejected</code> is called, the returned promise will resolve based on the return value of this call, or reject with the thrown error from this call. If the current promise fulfills, <code>onRejected</code> is not called and the returned promise fulfills to the same value.</p>"}},{"type":"prose","value":{"id":"description","title":"Description","isH3":false,"content":"<p>The <code>catch</code> method is used for error handling in promise composition. Since it returns a <a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise\"><code>Promise</code></a>, it <a href=\"/en-US/docs/Web/JavaScript/Guide/Using_promises#chaining_after_a_catch\">can be chained</a> in the same way as its sister method, <a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then\"><code>then()</code></a>.</p>\n<p>If a promise becomes rejected, and there are no rejection handlers to call (a handler can be attached through any of <a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then\"><code>then()</code></a>, <code>catch()</code>, or <a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally\"><code>finally()</code></a>), then the rejection event is surfaced by the host. In the browser, this results in an <a href=\"/en-US/docs/Web/API/Window/unhandledrejection_event\"><code>unhandledrejection</code></a> event. If a handler is attached to a rejected promise whose rejection has already caused an unhandled rejection event, then another <a href=\"/en-US/docs/Web/API/Window/rejectionhandled_event\"><code>rejectionhandled</code></a> event is fired.</p>\n<p><code>catch()</code> internally calls <code>then()</code> on the object upon which it was called, passing <code>undefined</code> and <code>onRejected</code> as arguments. The value of that call is directly returned. This is observable if you wrap the methods.</p>\n<div class=\"code-example\"><div class=\"example-header\"><span class=\"language-name\">js</span></div><pre class=\"brush: js notranslate\"><code>// overriding original Promise.prototype.then/catch just to add some logs\n((Promise) =&gt; {\n  const originalThen = Promise.prototype.then;\n  const originalCatch = Promise.prototype.catch;\n\n  Promise.prototype.then = function (...args) {\n    console.log(\"Called .then on %o with arguments: %o\", this, args);\n    return originalThen.apply(this, args);\n  };\n  Promise.prototype.catch = function (...args) {\n    console.error(\"Called .catch on %o with arguments: %o\", this, args);\n    return originalCatch.apply(this, args);\n  };\n})(Promise);\n\n// calling catch on an already resolved promise\nPromise.resolve().catch(function XXX() {});\n\n// Logs:\n// Called .catch on Promise{} with arguments: Arguments{1} [0: function XXX()]\n// Called .then on Promise{} with arguments: Arguments{2} [0: undefined, 1: function XXX()]\n</code></pre></div>\n<p>This means that passing <code>undefined</code> still causes the returned promise to be rejected, and you have to pass a function to prevent the final promise from being rejected.</p>\n<p>Because <code>catch()</code> just calls <code>then()</code>, it supports subclassing.</p>\n<div class=\"notecard note\">\n<p><strong>Note:</strong>\nThe examples below are throwing instances of <a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error\"><code>Error</code></a>. As with synchronous <a href=\"/en-US/docs/Web/JavaScript/Reference/Statements/throw\"><code>throw</code></a> statements, this is considered a good practice; otherwise, the part doing the catching would have to perform checks to see if the argument was a string or an error, and you might lose valuable information such as stack traces.</p>\n</div>"}},{"type":"prose","value":{"id":"examples","title":"Examples","isH3":false,"content":""}},{"type":"prose","value":{"id":"using_and_chaining_the_catch_method","title":"Using and chaining the catch() method","isH3":true,"content":"<div class=\"code-example\"><div class=\"example-header\"><span class=\"language-name\">js</span></div><pre class=\"brush: js notranslate\"><code>const p1 = new Promise((resolve, reject) =&gt; {\n  resolve(\"Success\");\n});\n\np1.then((value) =&gt; {\n  console.log(value); // \"Success!\"\n  throw new Error(\"oh, no!\");\n})\n  .catch((e) =&gt; {\n    console.error(e.message); // \"oh, no!\"\n  })\n  .then(\n    () =&gt; console.log(\"after a catch the chain is restored\"), // \"after a catch the chain is restored\"\n    () =&gt; console.log(\"Not fired due to the catch\"),\n  );\n\n// The following behaves the same as above\np1.then((value) =&gt; {\n  console.log(value); // \"Success!\"\n  return Promise.reject(\"oh, no!\");\n})\n  .catch((e) =&gt; {\n    console.error(e); // \"oh, no!\"\n  })\n  .then(\n    () =&gt; console.log(\"after a catch the chain is restored\"), // \"after a catch the chain is restored\"\n    () =&gt; console.log(\"Not fired due to the catch\"),\n  );\n</code></pre></div>"}},{"type":"prose","value":{"id":"gotchas_when_throwing_errors","title":"Gotchas when throwing errors","isH3":true,"content":"<p>Throwing an error will call the <code>catch()</code> method most of the time:</p>\n<div class=\"code-example\"><div class=\"example-header\"><span class=\"language-name\">js</span></div><pre class=\"brush: js notranslate\"><code>const p1 = new Promise((resolve, reject) =&gt; {\n  throw new Error(\"Uh-oh!\");\n});\n\np1.catch((e) =&gt; {\n  console.error(e); // \"Uh-oh!\"\n});\n</code></pre></div>\n<p>Errors thrown inside asynchronous functions will act like uncaught errors:</p>\n<div class=\"code-example\"><div class=\"example-header\"><span class=\"language-name\">js</span></div><pre class=\"brush: js notranslate\"><code>const p2 = new Promise((resolve, reject) =&gt; {\n  setTimeout(() =&gt; {\n    throw new Error(\"Uncaught Exception!\");\n  }, 1000);\n});\n\np2.catch((e) =&gt; {\n  console.error(e); // This is never called\n});\n</code></pre></div>\n<p>Errors thrown after <code>resolve</code> is called will be silenced:</p>\n<div class=\"code-example\"><div class=\"example-header\"><span class=\"language-name\">js</span></div><pre class=\"brush: js notranslate\"><code>const p3 = new Promise((resolve, reject) =&gt; {\n  resolve();\n  throw new Error(\"Silenced Exception!\");\n});\n\np3.catch((e) =&gt; {\n  console.error(e); // This is never called\n});\n</code></pre></div>"}},{"type":"prose","value":{"id":"catch_is_not_called_if_the_promise_is_fulfilled","title":"catch() is not called if the promise is fulfilled","isH3":true,"content":"<div class=\"code-example\"><div class=\"example-header\"><span class=\"language-name\">js</span></div><pre class=\"brush: js notranslate\"><code>// Create a promise which would not call onReject\nconst p1 = Promise.resolve(\"calling next\");\n\nconst p2 = p1.catch((reason) =&gt; {\n  // This is never called\n  console.error(\"catch p1!\");\n  console.error(reason);\n});\n\np2.then(\n  (value) =&gt; {\n    console.log(\"next promise's onFulfilled\");\n    console.log(value); // calling next\n  },\n  (reason) =&gt; {\n    console.log(\"next promise's onRejected\");\n    console.log(reason);\n  },\n);\n</code></pre></div>"}},{"type":"specifications","value":{"id":"specifications","title":"Specifications","isH3":false,"specifications":[{"bcdSpecificationURL":"https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise.prototype.catch","title":"ECMAScript Language Specification"}],"query":"javascript.builtins.Promise.catch"}},{"type":"browser_compatibility","value":{"id":"browser_compatibility","title":"Browser compatibility","isH3":false,"query":"javascript.builtins.Promise.catch"}},{"type":"prose","value":{"id":"see_also","title":"See also","isH3":false,"content":"<ul>\n<li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise\"><code>Promise</code></a></li>\n<li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then\"><code>Promise.prototype.then()</code></a></li>\n<li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally\"><code>Promise.prototype.finally()</code></a></li>\n</ul>"}}],"isActive":true,"isMarkdown":true,"isTranslated":false,"locale":"en-US","mdn_url":"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch","modified":"2024-07-25T22:06:52.000Z","native":"English (US)","noIndexing":false,"other_translations":[{"locale":"de","title":"Promise.prototype.catch()","native":"Deutsch"},{"locale":"es","title":"Promise.prototype.catch()","native":"Español"},{"locale":"fr","title":"Promise.prototype.catch()","native":"Français"},{"locale":"ja","title":"Promise.prototype.catch()","native":"日本語"},{"locale":"ko","title":"Promise.prototype.catch()","native":"한국어"},{"locale":"pt-BR","title":"Promise.prototype.catch()","native":"Português (do Brasil)"},{"locale":"ru","title":"Promise.prototype.catch()","native":"Русский"},{"locale":"zh-CN","title":"Promise.prototype.catch()","native":"中文 (简体)"},{"locale":"zh-TW","title":"Promise.prototype.catch()","native":"正體中文 (繁體)"}],"pageTitle":"Promise.prototype.catch() - JavaScript | MDN","parents":[{"uri":"/en-US/docs/Web","title":"References"},{"uri":"/en-US/docs/Web/JavaScript","title":"JavaScript"},{"uri":"/en-US/docs/Web/JavaScript/Reference","title":"Reference"},{"uri":"/en-US/docs/Web/JavaScript/Reference/Global_Objects","title":"Standard built-in objects"},{"uri":"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise","title":"Promise"},{"uri":"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch","title":"Promise.prototype.catch()"}],"popularity":null,"short_title":"Promise.prototype.catch()","sidebarHTML":"<ol><li class=\"section\"><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects\">Standard built-in objects</a></li><li class=\"section\"><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise\"><code>Promise</code></a></li><li class=\"toggle\"><details open=\"\"><summary>Constructor</summary><ol><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise\"><code>Promise() constructor</code></a></li></ol></details></li><li class=\"toggle\"><details open=\"\"><summary>Static methods</summary><ol><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all\"><code>Promise.all()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled\"><code>Promise.allSettled()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any\"><code>Promise.any()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race\"><code>Promise.race()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject\"><code>Promise.reject()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve\"><code>Promise.resolve()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/try\"><code>Promise.try()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers\"><code>Promise.withResolvers()</code></a></li></ol></details></li><li class=\"toggle\"><details open=\"\"><summary>Static properties</summary><ol><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Symbol.species\"><code>Promise[Symbol.species]</code></a></li></ol></details></li><li class=\"toggle\"><details open=\"\"><summary>Instance methods</summary><ol><li><em><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch\" aria-current=\"page\"><code>Promise.prototype.catch()</code></a></em></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally\"><code>Promise.prototype.finally()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then\"><code>Promise.prototype.then()</code></a></li></ol></details></li><li class=\"section\">Inheritance</li><li class=\"section\"><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object\"><code>Object/Function</code></a></li><li class=\"toggle\"><details><summary>Static methods</summary><ol><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply\"><code>Function.prototype.apply()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind\"><code>Function.prototype.bind()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call\"><code>Function.prototype.call()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString\"><code>Function.prototype.toString()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Symbol.hasInstance\"><code>Function.prototype[Symbol.hasInstance]()</code></a></li></ol></details></li><li class=\"toggle\"><details><summary>Static properties</summary><ol><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName\"><code>Function: displayName</code></a><abbr class=\"icon icon-nonstandard\" title=\"Non-standard. Check cross-browser support before using.\">\n<span class=\"visually-hidden\">Non-standard</span>\n</abbr></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length\"><code>Function: length</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name\"><code>Function: name</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/prototype\"><code>Function: prototype</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arguments\"><code>Function.prototype.arguments</code></a><abbr class=\"icon icon-nonstandard\" title=\"Non-standard. Check cross-browser support before using.\">\n<span class=\"visually-hidden\">Non-standard</span>\n</abbr><abbr class=\"icon icon-deprecated\" title=\"Deprecated. Not for use in new websites.\">\n<span class=\"visually-hidden\">Deprecated</span>\n</abbr></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/caller\"><code>Function.prototype.caller</code></a><abbr class=\"icon icon-nonstandard\" title=\"Non-standard. Check cross-browser support before using.\">\n<span class=\"visually-hidden\">Non-standard</span>\n</abbr><abbr class=\"icon icon-deprecated\" title=\"Deprecated. Not for use in new websites.\">\n<span class=\"visually-hidden\">Deprecated</span>\n</abbr></li></ol></details></li><li class=\"toggle\"><details><summary>Instance methods</summary><ol><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__\"><code>Object.prototype.__defineGetter__()</code></a><abbr class=\"icon icon-deprecated\" title=\"Deprecated. Not for use in new websites.\">\n<span class=\"visually-hidden\">Deprecated</span>\n</abbr></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineSetter__\"><code>Object.prototype.__defineSetter__()</code></a><abbr class=\"icon icon-deprecated\" title=\"Deprecated. Not for use in new websites.\">\n<span class=\"visually-hidden\">Deprecated</span>\n</abbr></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__lookupGetter__\"><code>Object.prototype.__lookupGetter__()</code></a><abbr class=\"icon icon-deprecated\" title=\"Deprecated. Not for use in new websites.\">\n<span class=\"visually-hidden\">Deprecated</span>\n</abbr></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__lookupSetter__\"><code>Object.prototype.__lookupSetter__()</code></a><abbr class=\"icon icon-deprecated\" title=\"Deprecated. Not for use in new websites.\">\n<span class=\"visually-hidden\">Deprecated</span>\n</abbr></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty\"><code>Object.prototype.hasOwnProperty()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isPrototypeOf\"><code>Object.prototype.isPrototypeOf()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/propertyIsEnumerable\"><code>Object.prototype.propertyIsEnumerable()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toLocaleString\"><code>Object.prototype.toLocaleString()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString\"><code>Object.prototype.toString()</code></a></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf\"><code>Object.prototype.valueOf()</code></a></li></ol></details></li><li class=\"toggle\"><details><summary>Instance properties</summary><ol><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto\"><code>Object.prototype.__proto__</code></a><abbr class=\"icon icon-deprecated\" title=\"Deprecated. Not for use in new websites.\">\n<span class=\"visually-hidden\">Deprecated</span>\n</abbr></li><li><a href=\"/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor\"><code>Object.prototype.constructor</code></a></li></ol></details></li></ol>","source":{"folder":"en-us/web/javascript/reference/global_objects/promise/catch","github_url":"https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/catch/index.md","last_commit_url":"https://github.com/mdn/content/commit/a4675b9077ae32f989c7ecac94f454db2653c4fc","filename":"index.md"},"summary":"The catch() method of Promise instances schedules a function to be called when the promise is rejected. It immediately returns another Promise object, allowing you to chain calls to other promise methods. It is a shortcut for then(undefined, onRejected).","title":"Promise.prototype.catch()","toc":[{"text":"Try it","id":"try_it"},{"text":"Syntax","id":"syntax"},{"text":"Description","id":"description"},{"text":"Examples","id":"examples"},{"text":"Specifications","id":"specifications"},{"text":"Browser compatibility","id":"browser_compatibility"},{"text":"See also","id":"see_also"}],"baseline":{"baseline":"high","baseline_low_date":"2015-07-29","baseline_high_date":"2018-01-29","support":{"chrome":"32","chrome_android":"32","edge":"12","firefox":"29","firefox_android":"29","safari":"8","safari_ios":"8"}},"browserCompat":["javascript.builtins.Promise.catch"],"pageType":"javascript-instance-method"}}</script>

</body><!-- Mirrored from developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 08 Jan 2025 13:10:15 GMT --></html>